// Speaker script content for deck v3 (academic physiotherapy audience).
// Each slide: key point, talking points (<b> marks the words to land), cues and a bridge.
// Two optional layers: "plain" (say it this way for junior colleagues) and
// "appraise" (use only if challenged; not part of the timed script).
// "verbatim: true" marks lines to say word for word. "src" holds the APA 7 in-text citations
// for the slide; the full reference list (all authors) comes from refs.js.
module.exports = {
  sections: [
    { from: 1, num: '', name: 'Opening', time: '3:35', note: 'Story first, then the physiotherapy lens and four objectives.' },
    { from: 7, num: '01', name: 'The vessel', time: '5:30', note: 'Why a small artery gives way, and what its location predicts.' },
    { from: 16, num: '02', name: 'The first hours', time: '3:25', note: 'Rupture, growth and pressure. The golf-ball moment lives here.' },
    { from: 22, num: '03', name: 'The days after', time: '2:50', note: 'How the blood itself keeps injuring the brain.' },
    { from: 27, num: '04', name: 'At the bedside', time: '5:50', note: 'When to start, a Day-4 case, the recovery debate, then close on Jill.' },
    { from: 35, num: '', name: 'Questions', time: '', note: 'Leave the references up while you take questions.' },
  ],
  slides: [
    { n: 1, src: '(Rossi & Cordonnier, 2014)', time: '0:20', title: 'When the vessel breaks', key: 'Introduce the chapter and the physiotherapy lens, then turn to one person.', verbatim: true,
      say: ['Good evening. My chapter is <b>Chapter 5</b> of the Oxford Textbook of Stroke: the pathophysiology of non-traumatic intracerebral haemorrhage.', 'Tonight I want to read it <b>as physiotherapists</b>: what the mechanism tells us about the patient in front of us.', 'But I want to start with <b>one person</b>.'],
      cues: [['pause', 'Walk to the centre and stand still before you say a word.']], next: 'Advance to the date.' },
    { n: 2, src: '(Taylor, 2008a, 2008b)', time: '0:25', title: '10 December 1996', key: 'A brain scientist wakes up with a bleed of her own.',
      say: ['<b>10 December 1996. Seven in the morning.</b>', 'A 37-year-old scientist wakes up with a <b>pounding pain behind her left eye</b>. She thinks it\'s a headache and climbs onto her exercise machine anyway.', 'Her name is <b>Jill Bolte Taylor</b>. She is a neuroanatomist. She studies the brain for a living.'],
      cues: [['slow', 'Tell it like a story. Slow down.'], ['pause', 'Pause after "for a living".']], next: 'Advance: the red dot grows.' },
    { n: 3, src: '(Taylor, 2008a, 2008b)', time: '0:40', title: 'Within four hours', key: 'In four hours she lost her balance, her arm and her speech.',
      say: ['Over the next <b>four hours</b>, she watches her own brain fail. First her balance, then her right arm, then her speech.', 'She tries to call for help, and the numbers on the phone look like <b>squiggles</b>.', 'A blood vessel had <b>burst</b> in the left side of her brain.'],
      cues: [['ask', 'Show of hands: "Who here has treated someone in the first week after a bleed like this?" Say what you see.']], next: '"Tonight is about what happened inside Jill\'s head, hour by hour."' },
    { n: 4, src: '(van Asch et al., 2010)', time: '0:35', title: '40%', key: 'Four in ten die within a month, and that did not improve for decades.',
      say: ['<b>Forty percent.</b> That is how many people die within a month of an intracerebral haemorrhage.', 'That number <b>did not move between 1980 and 2008</b>, while treatment for ischaemic stroke was transformed.', 'Part of the problem: we treat a bleed as <b>one moment</b>. The vessel bursts, the damage is done, and we wait.'],
      plain: 'Four in ten people with a brain bleed die within a month.',
      appraise: 'van Asch et al. (2010) pooled 36 population studies up to 2008. Part of the figure may be a self-fulfilling prophecy from early withdrawal of care (Becker et al., 2001).',
      cues: [['point', 'Point at the number and stay silent for two seconds.']], next: '"Chapter 5 gives us a different view."' },
    { n: 5, src: '(Rossi & Cordonnier, 2014)', time: '0:40', title: 'ICH is a process, not a moment', key: 'The headline of the whole talk.', verbatim: true,
      say: ['<b>ICH is a process, not a moment.</b>', 'The <b>vessel</b> decides where it bleeds. The <b>first hours</b> decide how big it gets. Over the following <b>days</b>, the blood itself keeps injuring the brain.', 'Each stage is a <b>window where we can act</b>.'],
      cues: [['pause', 'Say the headline slowly, then pause for two seconds.']], next: '"Here\'s what you\'ll be able to do by the end."' },
    { n: 6, src: '(Levett-Jones et al., 2010)', time: '0:55', title: 'Four things you will be able to do', key: 'Set four objectives, and tell the room how to listen.',
      say: ['By the end you will be able to <b>explain</b> why a bleed keeps injuring the brain, <b>predict</b> the impairment and the risk of decline, <b>appraise</b> the strength of each claim, mine included, and <b>apply</b> it by timing therapy to the stage.', 'There are two ways to listen. <b>The title is the message.</b> New to stroke? Hold on to the titles.', '<b>The grey tag is the evidence</b>: the study design and its main limit. Experienced? Challenge the tags. I\'ll take challenges at the end.'],
      cues: [['point', 'Point at the dark card, then at a real tag on the next content slide.']], next: '"Stage one."' },

    { n: 7, time: '0:05', title: '01 · The vessel', key: 'Bridge into stage one.', divider: true,
      say: ['"Stage one. <b>The vessel.</b> Why does a small artery give way?"'], cues: [], next: '' },
    { n: 8, src: '(Meretoja et al., 2012)', time: '0:40', title: 'Hypertension and amyloid cause over half', key: 'Two small-vessel diseases cause more than half of all bleeds.',
      say: ['This is <b>SMASH-U</b>: just over a thousand patients in Helsinki, each sorted by cause.', 'Hypertension <b>35 percent</b>, amyloid angiopathy <b>20</b>. Together more than half, and both are diseases of small vessels. <b>One in five</b> had no clear cause.', 'Why should we care? The <b>cause predicts where it bleeds</b>, and where it bleeds predicts what we\'ll see.'],
      plain: 'Two diseases of tiny arteries cause most bleeds: high blood pressure and amyloid.',
      appraise: 'One centre in Helsinki (Meretoja et al., 2012). "Undetermined" shrinks the harder you look, so the split depends on the work-up.',
      cues: [['point', 'Point at the two red bars and stay silent for two seconds.']], next: '"So what do these two diseases do to a small artery?"' },
    { n: 9, src: '(Fisher, 1971; Rossi & Cordonnier, 2014)', time: '0:55', title: 'Two diseases, two sets of vessels', key: 'Hypertension damages deep arteries; amyloid damages surface arteries.',
      say: ['Left: a <b>healthy</b> artery. Thin wall, wide channel.', 'Middle: <b>hypertension</b> attacks the tiny perforating arteries deep in the brain. The wall turns thick and glassy, but <b>brittle</b>. The bulge is a Charcot–Bouchard microaneurysm.', 'Right: <b>amyloid angiopathy</b>. Beta-amyloid replaces the muscle in arteries on the surface of the brain. Mostly over 55.'],
      plain: 'High blood pressure makes deep arteries stiff and brittle. Amyloid makes surface arteries weak.',
      appraise: 'Charcot–Bouchard microaneurysms were described in 1868; their role in rupture is still debated (Fisher, 1971).',
      cues: [['point', 'Walk them left to right: say what it is, point at what matters, say what it means.']], next: '"That gives us a rule you can use tomorrow."' },
    { n: 10, src: '(Macellari et al., 2014; Meretoja et al., 2012)', time: '0:25', title: 'Where it bleeds: deep', key: 'Deep bleed: think hypertension.',
      say: ['<b>Where it bleeds tells you why.</b>', 'These two are <b>deep</b>: the putamen and the thalamus. The pons and cerebellum count too.', 'These arteries branch at <b>right angles</b> off big, high-pressure trunks, so they take the full force of the pressure.'],
      plain: 'A deep bleed usually means a blood-pressure disease.',
      cues: [['point', 'Point to the two deep bleeds.']], next: 'Advance: a third bleed appears near the surface.' },
    { n: 11, src: '(Macellari et al., 2014; Zhu et al., 1997)', time: '0:25', title: 'Where it bleeds: lobar', key: 'Lobar bleed in an older adult: think amyloid. Young or atypical: be suspicious.',
      say: ['This one is <b>lobar</b>: the cortex and the white matter just beneath it.', 'In an <b>older adult</b>, think amyloid. In a <b>younger</b> person, or when something looks unusual, be <b>suspicious</b>.'],
      plain: 'A bleed near the surface in an older person usually means amyloid. In a young person, look for a hidden cause.',
      cues: [], next: '"Keep that thought. But first: what does location mean for us?"' },
    { n: 12, src: '(Gupta et al., 2025; Murray et al., 2025; Puig et al., 2019)', time: '1:00', title: 'Location predicts the impairment', key: 'Where the bleed sits predicts what you will see on assessment.',
      say: ['<b>Putamen and internal capsule:</b> weakness on the opposite side. Check the <b>PLIC</b>, where the motor fibres run. Clot on it: worse motor outcome.', '<b>Thalamus:</b> opposite-side sensory loss and ataxia; weeks later, sometimes central post-stroke pain.', '<b>Cerebellum:</b> same-side ataxia and truncal sway. It can block CSF and press on the brainstem, so <b>a drowsy cerebellar patient is an emergency</b>.', '<b>Pons:</b> often severe: four-limb weakness, cranial nerve signs. <b>Lobar:</b> by lobe, plus more seizures because the cortex is involved.'],
      plain: 'Read where the bleed is on the scan report. It tells you what to assess first.',
      appraise: 'PLIC: three imaging cohorts. Puig et al. (2019), n = 43: PLIC plus motor score above 6, AUC 0.89, PPV 65%, NPV 92%. Murray et al. (2025), 98 MISTIE III scans: PLIC overlap on routine CT predicted worse motor outcome, but inter-rater κ was only 0.45. Gupta et al. (2025), n = 305, held up in a validation cohort. A predictor, not a sentence.',
      cues: [['slow', 'This is the slide physiotherapists will photograph. Give each row a breath.']], next: '"MRI shows us the footprints of these diseases."' },
    { n: 13, src: '(Cordonnier et al., 2007; Knudsen et al., 2001)', time: '0:35', title: 'Microbleeds are the footprints', key: 'Microbleeds on MRI reveal which disease is at work.',
      say: ['Microbleeds are tiny old leaks of blood: <b>black dots</b> on MRI.', '<b>Surface</b> dots point to amyloid. <b>Deep</b> dots point to hypertension.', 'Charlotte Cordonnier, <b>one of this chapter\'s authors</b>, found them in <b>60 percent</b> of people with ICH, against 5 percent of healthy adults.'],
      plain: 'Black dots on MRI are old, tiny bleeds.',
      appraise: 'The 60% pools studies with different MRI sequences and field strengths (Cordonnier et al., 2007). More sensitive sequences find more, so the figure depends on the scanner.',
      cues: [], next: '"Your turn."' },
    { n: 14, src: '(Taylor, 2008b)', time: '0:45', title: 'Jill: primary or secondary?', key: 'Let the room work out Jill\'s diagnosis. Soft break 1, at about minute 8.',
      say: ['Jill was <b>37</b>. She had <b>no history of high blood pressure</b>. Her bleed was <b>lobar</b>.', 'Primary small-vessel disease, or a secondary cause? <b>Turn to the person next to you. Thirty seconds.</b>'],
      cues: [['ask', 'Stop talking. Count to 30 in your head, then ask two people for their answer. Online: "type primary or secondary in the chat".']], next: 'Advance: "Secondary."' },
    { n: 15, src: '(Taylor, 2008b; Zhu et al., 1997)', time: '0:40', title: 'Secondary: an AVM', key: 'Jill\'s profile was a textbook warning sign for a hidden lesion.',
      say: ['<b>Secondary.</b> Jill had an <b>arteriovenous malformation</b>, a tangle of vessels with no capillaries in between.', 'In 206 patients who all had angiography, <b>65 percent</b> of young, normotensive patients with a lobar bleed had a lesion. Over 45, hypertensive, deep bleed: <b>zero</b>.', '<b>The patient\'s story tells you where to look.</b>'],
      appraise: 'One Hong Kong centre, catheter angiography in everyone (Zhu et al., 1997). CT angiography has since changed screening (Macellari et al., 2014).',
      cues: [], next: '"Stage two."' },

    { n: 16, time: '0:05', title: '02 · The first hours', key: 'Bridge into stage two.', divider: true,
      say: ['"Stage two. <b>The first hours.</b> Jill had four of them."'], cues: [], next: '' },
    { n: 17, src: '(Fisher, 1971)', time: '0:35', title: 'One rupture can trigger more', key: 'A bleed keeps spreading by tearing the vessels around it.',
      say: ['<b>One:</b> a diseased vessel ruptures. <b>Two:</b> blood splits the tissue and a haematoma forms.', '<b>Three</b> is the surprise. Miller Fisher, 1971, found extra bleeding points at the edge: the growing clot tears its neighbours. An <b>avalanche</b>.', '<b>Four:</b> the bleeding stops when tissue pressure and clotting finally win.'],
      plain: 'The growing clot tears the small vessels around it, and they bleed too.',
      appraise: 'Fisher\'s (1971) evidence is autopsy: it shows a mechanism, not how often it happens. The CT data on the next slide show how often (Brott et al., 1997).',
      cues: [['point', 'Move left to right across the four pictures.']], next: '"So how often does the bleeding keep going?"' },
    { n: 18, src: '(Brott et al., 1997)', time: '0:30', title: 'How many bleeds keep growing?', key: 'Get the room to commit to a guess. Soft break 2, at about minute 10.',
      say: ['Here are <b>100 patients</b>, all scanned within three hours of onset.', 'How many bleeds keep growing? <b>A, five. B, fifteen. C, forty.</b>'],
      cues: [['ask', 'Hands up for each option. Say what you see: "Most of you went for B."']], next: 'Advance: the dots colour in.' },
    { n: 19, src: '(Brott et al., 1997; Davis et al., 2006)', time: '0:50', title: '38 in 100 keep growing', key: '38 in 100 bleeds keep growing, and growth predicts death.',
      say: ['<b>Thirty-eight.</b> <b>26</b> grew by more than a third within an hour of the first scan, <b>12 more</b> within twenty hours, with neurological decline.', 'This is <b>Jill\'s four hours</b>. Every 10 percent of growth raised the risk of death by <b>5 percent</b>.', 'For us, this is why <b>neuro observations come before any handling</b> in the first day.'],
      plain: 'More than a third of bleeds keep growing in the first day.',
      appraise: 'Brott et al. (1997): n = 103 within 3 h; growth defined as more than a third. PREDICT used more than 6 mL or 33% (Demchuk et al., 2012), so rates vary with the definition and scan timing.',
      cues: [['pause', 'Wait for the dots to finish colouring before you speak.']], next: '"Jill\'s surgeons found out how big hers got."' },
    { n: 20, src: '(Broderick et al., 1993; Taylor, 2008b)', time: '0:50', title: 'Jill\'s clot was the size of a golf ball', key: 'Small changes in size are deadly, and easy to miss. Your jaw-dropping moment.',
      say: ['Jill\'s surgeons removed a clot <b>this size</b>. A golf ball: about <b>40 millilitres</b>.', 'Grow it to 60, the dashed line. A clot that grows by a third looks only <b>10 percent wider</b> on a scan. The patient feels every millilitre.', 'At 60 millilitres with a GCS of 8 or less, predicted 30-day mortality was <b>91 percent</b>.'],
      appraise: '1990s Cincinnati care (Broderick et al., 1993), when early withdrawal of support was common: scores can become self-fulfilling prophecies (Becker et al., 2001). Use them to inform, never to decide.',
      cues: [['prop', 'Take the golf ball out BEFORE you speak. Hold it at shoulder height; three seconds of silence. Put it down where everyone can still see it.']], next: '"Why does volume matter so much?"' },
    { n: 21, src: '(Hanley, 2009)', time: '0:35', title: 'The skull is a closed box', key: 'Inside a closed skull, extra volume becomes extra pressure.',
      say: ['<b>The skull is a closed box.</b> As the clot grows, pressure rises; if it keeps rising, the brain shifts and can <b>herniate</b>.', 'About <b>45 percent</b> of bleeds break into the ventricles and can block CSF: <b>hydrocephalus</b>.', 'At the bedside, hydrocephalus looks like <b>drowsiness, headache and vomiting</b>. Hold that thought.'],
      plain: 'Hydrocephalus at the bedside: drowsy, headache, vomiting.',
      appraise: 'The ≈45% comes from a review of cohort data (Hanley, 2009). Rates vary with how early and how often patients are scanned.',
      cues: [['point', 'Trace the rings from the centre outwards.']], next: '"Stage three."' },

    { n: 22, time: '0:05', title: '03 · The days after', key: 'Bridge into stage three.', divider: true,
      say: ['"Stage three. <b>The bleeding has stopped. The injury has not.</b>"'], cues: [], next: '' },
    { n: 23, src: '(Gebel et al., 2002; Taylor, 2008b; Xi et al., 2006)', time: '0:50', title: 'Oedema builds in waves', key: 'Swelling builds in waves for up to two weeks.',
      say: ['<b>Hours:</b> the clot retracts and squeezes serum out. <b>Days 1–2:</b> thrombin opens the blood–brain barrier.', '<b>Day 3 on:</b> red cells break down and release iron. <b>Weeks:</b> scavenger cells clear the clot.', 'Oedema grew <b>75 percent</b> in the first 24 hours. <b>The days after are not a safe plateau.</b> Jill\'s surgery came 17 days later.'],
      plain: 'Swelling keeps building for days. Stable on day 1 does not mean stable on day 4.',
      appraise: 'The 75% comes from serial CT in hyperacute patients (Gebel et al., 2002). Measuring oedema on CT is imprecise.',
      cues: [['point', 'Move along the timeline, left to right.']], next: '"Three toxins drive this second wave."' },
    { n: 24, src: '(Selim et al., 2019; Xi et al., 2006)', time: '0:45', title: 'Three toxins, one result', key: 'Thrombin, iron and inflammation keep injuring the brain after the bleeding stops.',
      say: ['<b>Thrombin</b> first: needed to stop the bleed, toxic at high levels. <b>Iron</b> later, from burst red cells. <b>Inflammation</b> throughout.', 'All three end in the same place: leaky barrier, more swelling, dead neurons. <b>That is why patients get worse days later.</b>'],
      plain: 'The blood itself is toxic to the brain.',
      appraise: 'Mostly animal data (Xi et al., 2006). The best human test so far, i-DEF with deferoxamine, was neutral (Selim et al., 2019). Mechanism is not yet treatment.',
      cues: [['point', 'Point to the dark bar at the end.']], next: '"True or false?"' },
    { n: 25, src: '(Zazulia et al., 2001)', time: '0:30', title: 'True or false?', key: 'Test a belief many clinicians hold. Soft break 3, at about minute 14.',
      say: ['"The dark rim around the clot is <b>starving tissue</b>, like the penumbra in an ischaemic stroke." <b>Hands up for true.</b>', 'For years people worried that lowering blood pressure would starve that rim.'],
      cues: [['ask', 'Count the hands and say what you see.']], next: 'Advance: "False."' },
    { n: 26, src: '(Butcher et al., 2013; Zazulia et al., 2001)', time: '0:40', title: 'False: the rim is resting, not starving', key: 'The rim around the clot is resting, not starving.',
      say: ['<b>False.</b> PET in 19 patients: blood flow in the rim <b>56 percent</b>, oxygen use even lower, <b>48 percent</b>. <b>Resting, not starving.</b>', 'In ICH ADAPT, lowering systolic pressure <b>below 150</b> did not reduce flow around the clot.', 'For us: follow the team\'s <b>blood pressure targets</b> during activity. Pressure still matters for growth.'],
      appraise: 'PET, n = 19, shows a mechanism (Zazulia et al., 2001). ICH ADAPT, n = 75, tested it, but its endpoint was CT perfusion, not function (Butcher et al., 2013).',
      cues: [['point', 'Point to each pair of bars in turn.']], next: '"So what does this mean for physiotherapy?"' },

    { n: 27, time: '0:10', title: '04 · At the bedside', key: 'Bridge into the physiotherapy section.', divider: true,
      say: ['"What does this mean for <b>physiotherapy</b>? Let\'s follow the patient through time: the first hours, the days after, the months of recovery."'], cues: [], next: '' },
    { n: 28, src: '(AVERT Trial Collaboration Group, 2015; Bernhardt et al., 2016; Kan et al., 2026; Liu et al., 2014; Yen et al., 2020, 2021)', time: '1:00', title: 'Early helps; very early and intense may not', key: 'Start early with short, frequent sessions, but not big in the first 24 hours.',
      say: ['<b>AVERT</b>, over 2000 patients, infarcts and bleeds: high-dose mobilisation within 24 hours gave <b>fewer good outcomes</b>, 46 against 50 percent.', '<b>Liu</b>, 243 patients with ICH: rehab within 48 hours, better function at six months and fewer deaths. <b>Yen</b>, 60 patients: out of bed at 24 to 72 hours, better motor function and walking, with no blood pressure instability.', 'Within AVERT, <b>shorter, more frequent sessions</b> did better. And 17 trials pooled in 2026: <b>certainty low</b>.', 'So: <b>early, short and frequent</b>, once the team says the patient is stable.'],
      plain: 'Start early, keep sessions short and frequent, and don\'t go big in the first 24 hours.',
      appraise: 'Liu et al. (2014): HR 4.44, 95% CI 1.24–15.87; few deaths, so a signal, not an effect size. AVERT\'s ICH subgroup leaned towards usual care with no significant interaction (AVERT Trial Collaboration Group, 2015). The dose analysis is observational within the trial, Class III (Bernhardt et al., 2016). In Kan et al. (2026), safety outcomes were too poorly reported to pool.',
      cues: [['point', 'Point to each bar in turn: red, then slate, then navy, then the dark strip.']], next: '"Now let\'s put it together."' },
    { n: 29, src: 'Composite teaching case', time: '1:00', title: 'Day 4: drowsier than yesterday', key: 'A bedside decision that the pathophysiology predicts. Soft break 4, at about minute 16½.',
      say: ['Mr K, 68, hypertensive: a <b>left putaminal bleed, 22 millilitres</b>, about half a golf ball. Yesterday he sat out for 20 minutes, GCS 15.', 'Today at 9 a.m.: <b>GCS 13, new headache, vomited once, BP 184 over 98.</b> You\'d planned sit-to-stand practice.', '<b>A</b>: go ahead, but shorter. <b>B</b>: bed-level work only. <b>C</b>: hold and escalate.'],
      cues: [['ask', 'Hands up for A, B or C (or the chat online). Say what you see.']], next: 'Advance: "C."' },
    { n: 30, src: '(Levett-Jones et al., 2010)', time: '0:50', title: 'C: hold the session and escalate', key: 'New drowsiness after a bleed is the bleed talking until proven otherwise.',
      say: ['<b>Notice:</b> GCS down two, plus headache, vomiting and higher BP.', '<b>Interpret:</b> day 4, oedema still building. Or growth, or hydrocephalus, the closed box. Working out which is the medical team\'s job.', '<b>Act:</b> stop, tell the team now, repeat the obs. <b>Reflect:</b> the timeline predicted this. <b>"Not today" is a clinical decision, not a failure.</b>'],
      plain: 'New drowsiness, headache or vomiting: don\'t start. Tell the team now.',
      appraise: 'The cycle is adapted from Levett-Jones et al. (2010). Working out the cause is the medical team\'s job; ours is to notice the change, stop and escalate.',
      cues: [['point', 'Walk the four steps, then trace the return arrow.']], next: '"Families ask us about recovery."' },
    { n: 31, src: '(Balk et al., 2026; Kelly et al., 2003; Oosterveer et al., 2022; Paolucci et al., 2003; Salvadori et al., 2021; Yoo & Chung, 2026)', time: '1:10', title: 'It depends what you match', key: 'Whether bleeds recover better depends on how the comparison is matched.',
      say: ['Do bleeds recover better than infarcts? <b>Unmatched studies disagree</b>: Kelly found bigger gains; two newer studies, no difference.', '<b>Paolucci matched on the deficit</b>: bleeds did better, 2.5 times the odds of a big gain. <b>Balk matched on lesion size and site</b>: bleeds did worse.', 'Both fit Chapter 5. More of a bleed\'s deficit is <b>pressure, which resolves</b>. But the <b>blood itself is toxic</b>.', 'So: don\'t promise a better recovery, and <b>don\'t set a ceiling early</b>. After severe deep bleeds, most motor gains came in the first four months.'],
      plain: 'Don\'t promise a better recovery because it\'s a bleed. Don\'t give up early either.',
      appraise: 'All observational, survivors only; about 40% die within a month (van Asch et al., 2010). ICH patients start lower, so they have more room to gain on Barthel and FIM, which have ceiling effects. Paolucci et al. (2003): OR 2.48 (1.19–5.20). Balk et al. (2026): mRS OR 1.69 (1.02–2.79) favouring infarct. Yoo and Chung (2026): review of 25 studies.',
      cues: [['point', 'Grey dots first, then the dark dot, then the red dot.'], ['slow', 'Land "It depends what you match" slowly.']], next: '"So every stage is a window."' },
    { n: 32, src: '(AVERT Trial Collaboration Group, 2015; Bernhardt et al., 2016; Levett-Jones et al., 2010; Puig et al., 2019; Yoo & Chung, 2026)', time: '0:45', title: 'Every stage is a window to act', key: 'Each stage of the process gives physiotherapy a job. The heart of the talk.',
      say: ['<b>The vessel:</b> know the cause. Check BP before, during and after activity.', '<b>The first hours:</b> neuro obs first. Short, gentle sessions; nothing intense.', '<b>The days after:</b> screen before every session; expect ups and downs; <b>drowsy means escalate</b>.', '<b>The months after:</b> no early ceiling. Target what the location predicts.'],
      cues: [['slow', 'Slow right down. Give each row its own breath.']], next: '"If you remember three things from tonight…"' },
    { n: 33, src: '(Rossi & Cordonnier, 2014)', time: '0:20', title: 'If you remember three things', key: 'The three messages, one last time.', verbatim: true,
      say: ['The <b>vessel</b> decides where it bleeds.', 'The <b>first hours</b> decide how big it gets.', 'The <b>blood</b> keeps injuring the brain for days.'],
      cues: [['pause', 'Pause between each line.']], next: '"Back to Jill."' },
    { n: 34, src: '(Taylor, 2008a, 2008b)', time: '0:35', title: 'Eight years later', key: 'Close the story, land the big idea and invite challenge.', verbatim: true,
      say: ['Back to Jill. It took her <b>eight years</b> to recover. Then she walked onto the TED stage holding a real human brain.', 'Her bleed was not a moment. It was a process, and so was her recovery.', '<b>ICH is a process, not a moment.</b>', 'Thank you. <b>Which claim tonight would you challenge?</b>'],
      cues: [['pause', 'Three full seconds after the big idea. If the room is quiet, wait five seconds, then ask the back-up question below.']], next: 'Questions.' },
    { n: 35, time: '', title: 'References (slides 35–38)', key: 'Leave these up while you take questions.',
      say: ['Every figure in the talk is cited on its slide in APA style, and listed here with every author. <b>The chapter itself is Rossi and Cordonnier (2014).</b>', 'Hidden backups: type <b>39</b> and press Enter for other secondary causes, or <b>40</b> for what has changed since 2014.'], cues: [], next: '' },
  ],
  qa: [
    ['Liu\'s hazard ratio of 4.44 looks huge. Do you believe it?', 'As a signal, not an effect size. The 95% CI runs from 1.24 to 15.87, with few deaths and one country (Liu et al., 2014).'],
    ['AVERT was mostly infarcts. Why apply it to ICH?', 'It included bleeds, and the ICH subgroup leaned towards usual care, though the interaction was not significant (AVERT Trial Collaboration Group, 2015). So: caution in the first 24 h, not a ban. Yen et al. (2020) started at 24–72 h, outside that window.'],
    ['What blood pressure should stop a session?', 'Use the medical team\'s targets for that patient. No ICH trial gives a physiotherapy threshold. Early mobilisation did not raise BP variability (Yen et al., 2021).'],
    ['Is PLIC involvement on CT reliable?', 'Moderately: inter-rater κ was 0.45, better with expert readers (Murray et al., 2025). Combine it with the motor exam: PLIC plus motor score gave AUC 0.89 (Puig et al., 2019).'],
    ['Do bleeds recover better than infarcts?', 'It depends on matching. Matched on deficit: better (Paolucci et al., 2003). Matched on lesion size and site: worse (Balk et al., 2026).'],
    ['Why trust animal data on thrombin and iron?', 'We shouldn\'t fully. It explains the timing of decline (Xi et al., 2006), but deferoxamine was neutral in humans (Selim et al., 2019).'],
    ['Is the 40% figure out of date?', 'It covers studies to 2008 (van Asch et al., 2010), and early withdrawal of care can inflate it (Becker et al., 2001).'],
    ['Why do patients worsen on days 3–5?', 'Oedema still building, iron release (Xi et al., 2006) and hydrocephalus (Hanley, 2009); also pneumonia or seizures. Screen before every session.'],
    ['Which outcome measures would you use?', 'Match the measure to the question: FAC for walking, Fugl-Meyer for motor impairment, PASS for early postural control, as in Yen et al. (2020). Barthel and FIM have ceiling effects.'],
    ['How do you confirm amyloid angiopathy?', 'In life, the Boston criteria on MRI (Knudsen et al., 2001); version 2.0 added white-matter markers (Charidimou et al., 2022).'],
    ['Is lowering BP risky for the rim?', 'No. The rim is resting, not starving (Zazulia et al., 2001), and lowering systolic pressure below 150 did not reduce flow (Butcher et al., 2013).'],
    ['A question you can\'t answer', '"Good question. I don\'t want to guess. I\'ll check the source and come back to you."'],
  ],
};
